# Generated by Django 2.2.5 on 2019-09-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='items_json',
            new_name='items',
        ),
    ]
