# Generated by Django 2.2.4 on 2019-09-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='slug',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant_name',
            name='dish_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant_name',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant_name',
            name='restaurant_address',
            field=models.CharField(max_length=100),
        ),
    ]
