# Generated by Django 2.2.4 on 2019-09-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190917_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdetails',
        ),
    ]
