# Generated by Django 2.2.4 on 2019-09-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
    ]
